Exclude some files from relocation (SCRD-8594)
SUSE-Cloud/venvjail pull request #4
Opened 2019-04-04 11:53 UTC by JanZerebecki

Add argument --relocate-shebang-exclude to not change the shebang in
these files. This is needed when some of the python files are only used
to be copied to other environments, but never executed in the venv.

2019-04-04 12:09 UTC, aplanas requested changes

2019-04-04 12:09 UTC, aplanas commented on venvjail.py
> +    subparser.add_argument('--relocate-shebang-exclude', metavar='PATH',
nit: for coherence with the `--relocate`, can we simply use something short as `--no-relocate-list`? Basically is because 'exclude' have a meaning in this venvjail (package to include and packages to exclude), and this parameter is not related with this concept.

2019-04-04 12:09 UTC, aplanas commented on venvjail.py
> +    def exclude(path):
This extra complicate and error prone (as are ad-hoc rules to naming files and path). I would recommend to use something like:

```python
import fnmatch

def exclude(path):
    retrun any(fnmatch.fnmatch(path, excl) for excl in no_relocate_list)
```

For example:

```python
>>> any(fnmatch.fnmatch('/usr/bin/somescript.py', excl) for excl in ['/usr/bin/some*.py', '/bin/setup.py'])
True

>>> any(fnmatch.fnmatch('/usr/bin/myscript.py', excl) for excl in ['/usr/bin/some*.py', '/bin/setup.py'])
False
```

2019-04-04 15:30 UTC, JanZerebecki commented on venvjail.py
> +    subparser.add_argument('--relocate-shebang-exclude', metavar='PATH',
Done

2019-04-04 15:30 UTC, JanZerebecki commented on venvjail.py
> +    def exclude(path):
Done

2019-04-05 04:39 UTC, aplanas approved these changes

2019-04-05 04:39 UTC, merged

2019-04-05 08:32 UTC, aplanas commented
@JanZerebecki if you want to make a new release to Rocky you will need to do the `osc service dr`